# Generated by Django 4.0.6 on 2023-10-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_fvto', models.DateField()),
                ('mp_ID_Super', models.IntegerField()),
                ('mp_TotalSinDto', models.IntegerField()),
                ('mp_TotalConDto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_tipo', models.CharField(max_length=30, verbose_name='Tipo de Pago')),
                ('mp_nombre', models.CharField(max_length=30, verbose_name='Nombre de Pago')),
                ('mp_numero', models.IntegerField(verbose_name='Numero Tarjeta')),
                ('mp_codigo', models.CharField(max_length=30, verbose_name='Codigo')),
                ('mp_fvto', models.CharField(max_length=4, verbose_name='Vto')),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_name', models.CharField(max_length=30, verbose_name='Nombre Supermercado')),
                ('super_direccion', models.CharField(max_length=30, verbose_name='Direccion Supermercado')),
                ('super_mail', models.EmailField(max_length=50, unique=True, verbose_name='Mail del Supermercado')),
                ('super_telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('cuit', models.IntegerField(unique=True, verbose_name='cuit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_name', models.CharField(max_length=30, verbose_name='Nombre Supermercado')),
                ('super_direccion', models.CharField(max_length=30, verbose_name='Direccion Supermercado')),
                ('super_mail', models.EmailField(max_length=50, unique=True, verbose_name='Mail del Supermercado')),
                ('super_telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('pago_name', models.CharField(max_length=30, verbose_name='Tipo de Cobro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('persona_apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('persona_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('persona_mail', models.EmailField(max_length=50, unique=True, verbose_name='Mail Personal')),
                ('persona_telefono', models.CharField(max_length=50, verbose_name='Telefono Personal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('persona_apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('persona_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('persona_mail', models.EmailField(max_length=50, unique=True, verbose_name='Mail Personal')),
                ('persona_telefono', models.CharField(max_length=50, verbose_name='Telefono Personal')),
                ('responsable_mail', models.EmailField(max_length=50, unique=True, verbose_name='Mail del Responsable')),
                ('responsable_telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('cuil', models.IntegerField(unique=True, verbose_name='cuil')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_billetera.super')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
