# Generated by Django 4.0.6 on 2023-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_fvto', models.DateField()),
                ('mp_ID_Super', models.IntegerField()),
                ('mp_TotalSinDto', models.IntegerField()),
                ('mp_TotalConDto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_tipo', models.CharField(max_length=30)),
                ('mp_nombre', models.CharField(max_length=30)),
                ('mp_numero', models.IntegerField()),
                ('mp_codigo', models.CharField(max_length=30)),
                ('mp_fvto', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_name', models.CharField(max_length=30)),
                ('super_direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_name', models.CharField(max_length=30)),
            ],
        ),
    ]
