# Generated by Django 4.0.6 on 2023-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_billetera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCU_banco', models.CharField(max_length=30, verbose_name='Nombre de Banco')),
                ('TCU_tarjeta', models.CharField(max_length=30, verbose_name='Tarjetas')),
            ],
        ),
        migrations.AlterField(
            model_name='responsable',
            name='persona_apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido     '),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='persona_direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion    '),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='persona_name',
            field=models.CharField(max_length=50, verbose_name='Nombre       '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona_apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido     '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona_direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion    '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona_name',
            field=models.CharField(max_length=50, verbose_name='Nombre       '),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usoTarjetas',
            field=models.ManyToManyField(to='core_billetera.tcu'),
        ),
    ]
